<?php
/**
 * MerchantVerticalsResponseTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Splitit
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * Splitit.OnBoarding.Api.V2
 *
 * Splitit's Onboarding API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Splitit\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * MerchantVerticalsResponseTest Class Doc Comment
 *
 * @category    Class
 * @description MerchantVerticalsResponse
 * @package     Splitit
 */
class MerchantVerticalsResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "MerchantVerticalsResponse"
     */
    public function testMerchantVerticalsResponse()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "merchant_verticals"
     */
    public function testPropertyMerchantVerticals()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
