<?php
/**
 * MerchantVerticalResponseTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Splitit
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * Splitit.OnBoarding.Api.V2
 *
 * Splitit's Onboarding API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Splitit\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * MerchantVerticalResponseTest Class Doc Comment
 *
 * @category    Class
 * @description MerchantVerticalResponse
 * @package     Splitit
 */
class MerchantVerticalResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "MerchantVerticalResponse"
     */
    public function testMerchantVerticalResponse()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "vertical_display_name"
     */
    public function testPropertyVerticalDisplayName()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "vertical_splitit_name"
     */
    public function testPropertyVerticalSplititName()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sub_categories"
     */
    public function testPropertySubCategories()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
