<?php
/**
 * DataApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Splitit
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * Splitit.OnBoarding.Api.V2
 *
 * Splitit's Onboarding API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Splitit\Test\Api;

use \Splitit\Configuration;
use \Splitit\ApiException;
use \Splitit\ObjectSerializer;
use PHPUnit\Framework\TestCase;

class DataApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getCountries
     *
     * .
     *
     */
    public function testGetCountries()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCurrencies
     *
     * .
     *
     */
    public function testGetCurrencies()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProcessors
     *
     * .
     *
     */
    public function testGetProcessors()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getVerticals
     *
     * .
     *
     */
    public function testGetVerticals()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for statusLegend
     *
     * .
     *
     */
    public function testStatusLegend()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
